# Generated by Django 4.2.7 on 2025-11-08 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_empresa'),
        ('pricing', '0002_composicao_itemcomposicao_produto_delete_pricingrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição do Orçamento')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='draft', max_length=10)),
                ('custo_total_materias_primas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('custo_total_processos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('custo_total_despesas_impostos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('custo_total_producao', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('margem_lucro_percentual', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('preco_venda_calculado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('preco_venda_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='users.empresa')),
                ('produto_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.produto', verbose_name='Produto Base')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('custo_total_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.produto', verbose_name='Componente')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produto', to='quotes.orcamento')),
            ],
            options={
                'verbose_name': 'Item de Produto do Orçamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItemProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Processo')),
                ('horas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_total_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_processo', to='quotes.orcamento')),
            ],
            options={
                'verbose_name': 'Item de Processo do Orçamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItemDespesaImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor Fixo (R$)')], default='percentual', max_length=10)),
                ('base_calculo', models.CharField(choices=[('custo', 'Sobre Custo Total'), ('venda', 'Sobre Preço de Venda')], default='custo', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_total_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_despesa_imposto', to='quotes.orcamento')),
            ],
            options={
                'verbose_name': 'Item de Despesa/Imposto do Orçamento',
                'ordering': ['id'],
            },
        ),
    ]
