# Generated by Django 4.2.7 on 2025-11-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('discount', 'Desconto'), ('markup', 'Acréscimo'), ('custom', 'Cálculo Customizado')], max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Parâmetros do cálculo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Pricing',
                'verbose_name_plural': 'Regras de Pricing',
            },
        ),
    ]
