# Generated by Django 4.2.7 on 2025-11-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_empresa'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('custo_adicional_fixo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Fixo Adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes', to='users.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Composição (Receita)',
                'verbose_name_plural': 'Composições (Receitas)',
            },
        ),
        migrations.CreateModel(
            name='ItemComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Item da Composição',
                'verbose_name_plural': 'Itens da Composição',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Item')),
                ('codigo_sku', models.CharField(blank=True, max_length=100, verbose_name='Código (SKU)')),
                ('tipo', models.CharField(choices=[('MP', 'Matéria-Prima'), ('PA', 'Produto Acabado'), ('SV', 'Serviço'), ('SB', 'Sub-produto/Intermediário')], max_length=2, verbose_name='Tipo de Item')),
                ('unidade_medida', models.CharField(max_length=20, verbose_name='Unidade de Medida')),
                ('preco_custo', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Preço de Custo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='users.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Produto/Item',
                'verbose_name_plural': 'Produtos/Itens',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'codigo_sku')},
            },
        ),
        migrations.DeleteModel(
            name='PricingRule',
        ),
        migrations.AddField(
            model_name='itemcomposicao',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_em', to='pricing.produto', verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='itemcomposicao',
            name='composicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pricing.composicao', verbose_name='Composição'),
        ),
        migrations.AddField(
            model_name='composicao',
            name='produto_acabado',
            field=models.OneToOneField(limit_choices_to=models.Q(('tipo', 'MP'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='composicao', to='pricing.produto', verbose_name='Produto Acabado'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcomposicao',
            unique_together={('composicao', 'componente')},
        ),
        migrations.AlterUniqueTogether(
            name='composicao',
            unique_together={('empresa', 'produto_acabado')},
        ),
    ]
