# Generated by Django 4.2.7 on 2025-11-16 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_empresa'),
        ('pricing', '0002_composicao_itemcomposicao_produto_delete_pricingrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_produto', to='users.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Produto',
                'verbose_name_plural': 'Tipos de Produtos',
                'unique_together': {('empresa', 'nome'), ('empresa', 'tipo')},
            },
        ),
        migrations.AlterField(
            model_name='composicao',
            name='produto_acabado',
            field=models.OneToOneField(limit_choices_to=models.Q(('tipo__tipo', 'MP'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='composicao', to='pricing.produto', verbose_name='Produto Acabado'),
        ),
        migrations.CreateModel(
            name='TipoProdutoSequencia',
            fields=[
                ('tipo_produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sequencia', serialize=False, to='pricing.tipoproduto')),
                ('ultimo_numero', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sequencia de Produto',
                'verbose_name_plural': 'Sequencias de produto',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_medida', to='users.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': ('Unidade de Medida',),
                'verbose_name_plural': 'Unidades de Medida',
                'unique_together': {('empresa', 'nome'), ('empresa', 'sigla')},
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoProduto', to='pricing.tipoproduto', verbose_name='Tipo de Item'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidadeMedida', to='pricing.unidademedida', verbose_name='Unidade de Medida'),
        ),
    ]
