# Generated by Django 4.2.7 on 2025-11-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_tipoproduto_alter_composicao_produto_acabado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoProdutoSequencia',
        ),
    ]
