# Generated by Django 4.2.7 on 2025-11-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_delete_tipoprodutosequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Peso Bruto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_liquido',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Peso Liquido'),
        ),
        migrations.AddField(
            model_name='produto',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia'),
        ),
    ]
