# Generated by Django 4.2.7 on 2025-11-08 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email da empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_empresas', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário da Conta')),
            ],
            options={
                'verbose_name': 'Empresa (Tenant)',
                'verbose_name_plural': 'Empresas (Tenants)',
                'ordering': ['nome_fantasia'],
            },
        ),
    ]
