# Generated by Django 4.2.7 on 2025-11-16 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorSequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=50)),
                ('ultimo_numero', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contadores', to='users.empresa')),
            ],
            options={
                'verbose_name': 'Contador de Sequência',
                'verbose_name_plural': 'Contadores de Sequência',
                'indexes': [models.Index(fields=['empresa', 'chave'], name='core_contad_empresa_0e0feb_idx')],
                'unique_together': {('empresa', 'chave')},
            },
        ),
    ]
